### ISSUE TITLE
Question :D

### ISSUE THREAD

**Issue by Jacksweeney1** [crissyshan/Soviet-Rock-Songs#7]
Guys, 

Sorry for the late notice- 

I am looking through the Soviet-Rock-Songs folder(s) and am unable to find the XML doc i'm supposed to make into a schema. I will continue to search. Let me know if you know where I can obtain said XML.

**Comment by mjyb16** [comment]
Hey Jack,
I don’t think anyone has put up a completed xml song, but you can start on the schema using the structural markup patterns for lyrics (line, chorus, verse, etc) as well as start creating part of the schema based on the potential tags outlined in the “Dissidence” file. I will try to create the sample of songs later tonight so we can start marking up next week. Hope this helps!

**Comment by Jacksweeney1** [comment]
It does indeed good sir
